 
name: Node.js CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run Tests
      run: npm run test

    - name: Build
      run: npm run build

    - name: Deploy to Server
      run: |
        ssh user@server "cd /path/to/app && git pull origin main && pm2 restart ecosystem.config.js"
